# Criar branch automaticamente quando uma issue é criada
mode: auto
# Nome da branch
branchName: "SSG-${issue.number}"
# Fechar a issue automaticamente quando a branch mergeada
autoCloseIssue: true

# Baseados na tag.
branchs:
  - label: feature
    prefix: "feature/"
    branchName: "${issue.number}"

  - label: bug
    prefix: "bugfix/"
    branchName: "${issue.number}"

  - label: epic
    prefix: "release/"
    branchName: "${issue.milestone}"
